translate 5-network 01-fetch
javascript-tutorial/id.javascript.info pull request #134
Opened 2020-10-04 14:32 UTC by tiana30

2020-10-04 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/id.javascript.info?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/id.javascript.info?pullRequest=134) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/id.javascript.info?pullRequest=134) it.</sub>

2020-10-05 06:13 UTC, babul28 commented on 5-network/01-fetch/01-fetch-users/task.md
> +3. Jika ada permintaan yang gagal, atau jika tidak ada pengguna itu, fungsi tersebut harus mengembalikan `null` dalam senarai yang dihasilkan.
menurutku lebih bagus "Jika terdapat permintaan yang gagal atau pengguna (_user_) tersebut tidak ditemukan, maka fungsi tersebut harus mengembalikan `null` pada senarai yang dihasilkan"

2020-10-05 06:13 UTC, babul28 commented on 5-network/01-fetch/article.md
> +Without `options`, that is a simple GET permintaan, downloading the contents of the `url`.
Lupa gak di hapus?

2020-10-05 06:13 UTC, babul28 commented on 5-network/01-fetch/article.md
> +Browser segera memulai permintaan dan mengembalikan sebuah promise yang memanggil kode yang akan di pakai untuk mendapatkan hasil.
Penggunaan istilah inggris yang tidak ada padanan kata indonesianya mungkin bisa ditulis miring

2020-10-05 12:12 UTC, yoga1234 commented on 5-network/01-fetch/01-fetch-users/solution.md
> +Untuk mengambil pengguna kita membutuhkan `fetch('https://api.github.com/users/USERNAME')`.
Titik duanya sekalian dong :D

2020-10-05 12:14 UTC, yoga1234 commented on 5-network/01-fetch/01-fetch-users/solution.md
> +Ini adalah contoh bagaimana Promise API tingkat rendah masih bisa digunakan meskipun kita utamanya menggunakan ʻasync / await.
kata-kata async/awaitnya pake backtick `async / await`.

2020-10-05 12:16 UTC, yoga1234 commented on 5-network/01-fetch/01-fetch-users/task.md
> +url Github dengan informasi user yang diberikan nama `USERNAME` : `https://api.github.com/users/USERNAME`.
Awalannya pake kapital.. hehe

2020-10-05 12:17 UTC, yoga1234 commented on 5-network/01-fetch/01-fetch-users/task.md
> +1. Harus ada satu permintaan `fetch` setiap user.
Yang ini mungkin 
"Harus ada satu permintaan `fetch` untuk setiap user."
biar lebih enak..

2020-10-05 12:18 UTC, yoga1234 commented on 5-network/01-fetch/01-fetch-users/task.md
> +3. Jika ada permintaan yang gagal, atau jika tidak ada pengguna itu, fungsi tersebut harus mengembalikan `null` dalam senarai yang dihasilkan.
@babul28 Boleh kaya gini..

2020-10-05 12:21 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +Without `options`, that is a simple GET permintaan, downloading the contents of the `url`.
kayanya kelupaan.. hehe

2020-10-05 12:21 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +Browser segera memulai permintaan dan mengembalikan sebuah promise yang memanggil kode yang akan di pakai untuk mendapatkan hasil.
iya kak..

2020-10-05 12:25 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +- Sebagai tambahan, `response.body` adalah objek  [ReadableStream](https://streams.spec.whatwg.org/#rs-kelas), hal ini ini memungkinkan untuk membaca bagian tubuh demi bagian, kita akan melihat conto
bagian yang ini typo kayanya sama kurang pas.
"hal ini memungkinkan kamu untuk membaca bagian demi bagian _body_ .
Kaya gitu mungkin?

2020-10-05 12:29 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +## Response headers
Ini ko berubah jadi response?

2020-10-05 12:31 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +- `Access-Control-permintaan-Method`
Kode ini jangan diterjemahin soalnya ini kode _header_ buat _fetch_
`Access-Control-Request-Headers`
`Access-Control-Request-Method`

2020-10-05 12:32 UTC, yoga1234 commented on 5-network/01-fetch/article.md
> +## POST Response
Yang ini juga kayanya salah, request != response.. hehe

2020-10-05 12:36 UTC, yoga1234 requested changes
Ada beberapa komentar yang kayanya perlu diperbaiki..

Semangat Mba!! 🔥🔥🔥

2020-10-06 01:05 UTC, tiana30 commented
oke makasih banyak udah review saya perbaiki dulu ya.

2020-10-06 02:03 UTC, tiana30 commented on 5-network/01-fetch/article.md
> +- Sebagai tambahan, `response.body` adalah objek  [ReadableStream](https://streams.spec.whatwg.org/#rs-kelas), hal ini ini memungkinkan untuk membaca bagian tubuh demi bagian, kita akan melihat conto
tolong dong kasih rekomendasi file yang baru diterjemahin dan sudah di merge  biar saya pelajarin juga.

2020-10-06 11:29 UTC, babul28 commented on 5-network/01-fetch/article.md
> +- **`response.blob()`** -- mengembalikan tanggapan sebagai [Blob](info:blob) (data biner dengan tipe),
`binary data with type` kalau di translate "tipe untuk data biner" bagaimana @yoga1234 ?

2020-10-06 11:29 UTC, babul28 commented on 5-network/01-fetch/article.md
> +Untuk mendapatkan tanggapan teks, gunakan `await response.text()` daripada `.json()`:
Bagaimana kalau "Untuk mendapatkan data respon dengan format teks, .... ?

2020-10-06 11:29 UTC, babul28 commented on 5-network/01-fetch/article.md
> +//membuat <img> sebagai item
Bagaimana kalau diganti `membuat elemen <img>` ?

2020-10-06 11:29 UTC, babul28 commented on 5-network/01-fetch/article.md
> +Kita hanya bisa memilih satu dari metode membaca body.
Saya rasa ini kurang pas, kalau menurut saya disini konteksnya hanya bisa memilih satu dari beberapa metode yang ada (yang dijelaskan di line 64 ^^^) untuk membaca `response body`. jadi mungkin lebih mudah diapahami kalau dijelaskan seperti ini `Kita hanya bisa memilih satu dari beberapa metode untuk membaca body` :v:

2020-10-06 11:29 UTC, babul28 commented on 5-network/01-fetch/article.md
> +Jika kita sudah mendapatkan tanggapan dengan `response.text()` , maka `response.json()` tidak akan bekerja, karena isi body sudah di proses lebih awal.
Nah, maksud dari kalimat sebelumnya kan berhubungan dengan kalimat ini :v:

2020-10-08 11:35 UTC, tiana30 commented on 5-network/01-fetch/article.md
> +- **`response.blob()`** -- mengembalikan tanggapan sebagai [Blob](info:blob) (data biner dengan tipe),
oke

2020-10-08 11:39 UTC, tiana30 commented
/done

2020-10-11 12:28 UTC, yoga1234 approved these changes

2020-10-11 12:28 UTC, merged