Eval: run a code string
javascript-tutorial/id.javascript.info pull request #138
Opened 2020-10-06 15:24 UTC by raisoturu

2020-10-06 15:47 UTC, yoga1234 commented on 1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
> +Mari gunakan `eval` untuk mengitung rumus matematika:
typo gan..

2020-10-06 15:52 UTC, yoga1234 commented on 1-js/99-js-misc/02-eval/article.md
> +Harap dicatat bahwa kemampuannya untuk mengakses variabel luar mengakses variabel luar memiliki efek samping.
Ada kalimat dobel..

2020-10-06 15:54 UTC, yoga1234 requested changes
Ada beberapa komentar gan..

2020-10-06 15:59 UTC, raisoturu commented
resolved by 7043802f132faeebf4b020c713144eb30181e89b gan

2020-10-07 03:44 UTC, babul28 commented on 1-js/99-js-misc/02-eval/article.md
> +Alasannya sederhana: dulu JavaScript adalah bahasa yang jauh lebih lemah, banyak hal yang hanya bisa dilakukan dengan `eval`. Tapi wakti itu telah berlalu satu dekade yang lalu.
Ada typo mas "wakti"

2020-10-07 03:44 UTC, babul28 commented on 1-js/99-js-misc/02-eval/article.md
>  let code = 'alert("Hello")';
menurutku kalau kata Hello diterjemahkan ke indonesia juga gpp :v:

2020-10-07 03:44 UTC, babul28 commented on 1-js/99-js-misc/02-eval/article.md
>  **If eval'ed code doesn't use outer variables, please call `eval` as `window.eval(...)`:**
ini lupa diterjemahkan ya mas?

2020-10-07 09:20 UTC, raisoturu commented on 1-js/99-js-misc/02-eval/article.md
>  **If eval'ed code doesn't use outer variables, please call `eval` as `window.eval(...)`:**
Oiya kelewatan

2020-10-07 10:51 UTC, raisoturu commented
/done

2020-10-07 12:59 UTC, merged