Custom Elements - Elemen Kustom
javascript-tutorial/id.javascript.info pull request #139
Opened 2020-10-07 05:27 UTC by abdmmar

Selesai terjemah dari English ke Bahasa, mohon direview 🙏, terima kasih!

2020-10-07 13:08 UTC, yoga1234 commented on 8-web-components/2-custom-elements/1-live-timer/solution.md
> +1. Kita menghapus timer `setInterval` ketika elemen dihapus dari dokumen. Ini penting, jika tidak, timer terus berdetak bahkan jika tidak diperlukan lagi. Dan browser tidak dapat menghapus memori dar
Gan, yang kalimat yang terakhir "tidak dapat menghapus dari memori dan _yang_ direferensikan olehnya. " kayanya?

2020-10-07 13:10 UTC, yoga1234 commented on 8-web-components/2-custom-elements/1-live-timer/task.md
> +2. *Tick* (update) setiap detik.
Mungkin supaya jelas *Tick* nya diterjemahin jadi berdetik/berdetak? karena itu bukan nama fungsi atau elemen.

2020-10-07 13:25 UTC, yoga1234 commented on 8-web-components/2-custom-elements/article.md
> +1. Logika rendering dipindahkan ke `render()` helper method.
Yang ini lebih enak "Logika renderingnya dipindahkan ke metode helper `render()`" mungkin?

2020-10-07 13:28 UTC, yoga1234 commented on 8-web-components/2-custom-elements/article.md
> +3. Untuk perubahan sebuah atribut, cantumkan dalam `observedAttributes()`, `attributeChangedCallback` terpicu.
Yang ini kayanya kurang pas, gan.
kalo gini..
Untuk perubahan pada sebuah atribut, cantumkan dalam pemicu(?) `observedAttributes()`, `attributeChangedCallback`.
?

2020-10-07 13:36 UTC, yoga1234 requested changes
Terdapat beberapa komentar gan.. sama conflict

2020-10-07 14:37 UTC, abdmmar commented on 8-web-components/2-custom-elements/1-live-timer/task.md
> +2. *Tick* (update) setiap detik.
iya tadinya mau gitu hehehe, oke gan

2020-10-07 14:44 UTC, abdmmar commented on 8-web-components/2-custom-elements/article.md
> +1. Logika rendering dipindahkan ke `render()` helper method.
Kalo "Logika renderingnya dipindahkan ke _method_ helper `render()` " gmn gan?  biar konsisten aja sih penggunaan kata _method_nya

2020-10-07 14:45 UTC, abdmmar commented on 8-web-components/2-custom-elements/article.md
> +3. Untuk perubahan sebuah atribut, cantumkan dalam `observedAttributes()`, `attributeChangedCallback` terpicu.
oke gan

2020-10-07 14:52 UTC, abdmmar reviewed
Comment and conflict are resolved

2020-10-07 14:57 UTC, abdmmar commented
/done

2020-10-08 08:37 UTC, yoga1234 approved these changes

2020-10-08 08:38 UTC, merged