Modules, introduction
javascript-tutorial/id.javascript.info pull request #159
Opened 2020-10-24 03:29 UTC by tiana30

2020-11-06 15:35 UTC, juuni26 requested changes
tolong diperbaiki beberapa bahasanya gan. terima kasih telah membantu projek open source ini berkembang 👋

2020-11-06 15:35 UTC, juuni26 commented on 2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
> +Ada banyak cara untuk melakukan ini.
"to do it" bisa diubah menjadi melakukan itu atau melakukannya .

2020-11-06 15:35 UTC, juuni26 commented on 2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
> +// or
bisa diubah //or menjadi atau

2020-11-06 15:35 UTC, juuni26 commented on 2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
> +// 1. The table with `id="age-table"` (1. tabel dengan `id="age-table"`).
timpa aja gan sekalian ga perlu dipisahin jadi kurung yang lain. tolong perbaiki juga yang lain. kita minimalkan bahasa translate an, kecuali error yang keluar dari log error javascriptnya. bisa ditambahkan kurung seperti diatas.

2020-11-06 15:35 UTC, juuni26 commented on 2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
> +Bagaimana cara mencari?...
(optional) tambahkan imbuhan "nya" biar enak dibacanya.  "Bagaimana cara mencarinya?"

2020-11-13 12:51 UTC, tiana30 commented
/done

2020-11-16 11:16 UTC, juuni26 approved these changes
looks good :)

2020-11-30 06:44 UTC, merged

2020-12-15 11:24 UTC, tiana30 commented
halo saya mau ngasih tahu jadi file yang aku pull request disini kan ada dua yang satu modules: introduction dan yang satu Searching: getElement*, querySelector* jadi untuk file ini belum dicentang. apa harus di pull request lagi dengan judul file yang ini Searching: getElement*, querySelector*

2020-12-16 06:41 UTC, juuni26 commented
> halo saya mau ngasih tahu jadi file yang aku pull request disini kan ada dua yang satu modules: introduction dan yang satu Searching: getElement*, querySelector* jadi untuk file ini belum dicentang. apa harus di pull request lagi dengan judul file yang ini Searching: getElement*, querySelector*

oke done ya