Focusing: focus/blur
javascript-tutorial/id.javascript.info pull request #160
Opened 2020-10-24 20:34 UTC by Pazmy

2020-11-06 15:21 UTC, juuni26 requested changes
tolong diperbaiki beberapa bahasanya gan. terimakasih telah membantu projek open source ini berkembang 👋

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
> +- Tombol OK and CANCEL muncul di bawah sel untuk finish/cancel editing.
kata finish/cancel bisa diterjemahkan lagi , contoh kalimat: "tombol ok dan cancel muncul dibawah sel untuk menyelesaikan atau membatalkan proses sunting/perubahan."

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
> +- Hanya satu sel yang dapat diedit setiap saat. Sementara `<td>` dalam "edit mode", klik pada sel lain akan diabaikan.
saran tambahkan imbuhan "nya "agar menekankan di satu moment . "Hanya satu sel yang dapat diedit setiap saatnya"

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
> +Kita bisa gunakan `mouse.onclick` untuk menghandle klik dan membuat mouse "moveable/bergerak" dengan `position:fixed`, kemudian `mouse.onkeydown` untuk handle tombol panah.
menghandle bisa diubah menjadi menangani/mengatur

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
> +Satu-satunya jebakan ialah `keydown` hanya trigger pada elemen dengan fokus. Jadi kita perlu untuk menambahkan `tabindex` pada elemen. Karena kita dilarang mengubah HTML, kita bisa gunakan `mouse.tab
trigger bisa diubah menjadi memicu, contoh: `keydown` hanya memicu pada elemen yang memiliki fokus. dan properti bisa diletakkan didepan agar sesuai dengan kaidah bahasa , contoh : kita bisa gunakan properti`mouse.tabIndex` untuk itu.

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
> +P.S. Jangan letakkan event handler dimanapun kecuali elemen `#mouse`.
tambahkan kata "pada" agar lebih menjelaskan  dimana elemen mouse. contoh: "Jangan letakkan event handler dimanapun kecuali pada elemen `#mouse`."

2020-11-06 15:21 UTC, juuni26 commented on 2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
> +P.P.S. Jangan modif HTML/CSS, pendekatannya harus umum dan bekerja dengan elemen manapun.
modif bisa diubah menjadi kata yang lebih baku seperti ubah atau modifikasi sekalian.

2020-11-12 19:21 UTC, Pazmy commented
/done

2020-11-14 03:54 UTC, yoga1234 approved these changes

2020-11-16 11:14 UTC, merged